# --- Archlinux Base Config ---
- ifarch:
    - pacmanupdate:

    - pacman:
        - sudo
        - curl
        - python
        - python-pip
        - git
        - base-devel
        - kitty-terminfo

    - shell:
        - "git clone --depth 1 https://aur.archlinux.org/yay.git ~/yay"
        - "cd ~/yay && makepkg -si --noconfirm"

    - yayupdate:
