- defaults:
    link:
      force: true
      relink: true

- clean:
    ~/:
      force: true
    ~/.config:
      force: true
      recursive: true

- ifubuntu:
    - aptupdate:

- ifarch:
    - pacmanupdate:

- ifmacos:
    - bootstraphomebrew:
