- create:
  - ~/.local/bin

- link:
    ~/.local/bin/diffconflicts: bin/diffconflicts
    ~/.local/bin/doi2bib: bin/doi2bib
    ~/.local/bin/ftwind: bin/ftwind
    ~/.local/bin/ftpane: bin/ftpane
    ~/.local/bin/gzball: bin/gzball
    ~/.local/bin/ports: bin/ports
    ~/.local/bin/random: bin/random
    ~/.local/bin/shim: scripts/shim.sh
    ~/.local/bin/lock-screen:
      if: '[ `uname` = Darwin ]'
      path: bin/lock-screen
    ~/.local/bin/lyrics:
      if: '[ `uname` = Darwin ]'
      path: bin/lyrics
