- ifmacos:
  - tap:
      - homebrew/cask-fonts
  - cask:
      - font-hack-nerd-font

- ifanylinux:
    - shell:
        - git clone https://github.com/ryanoasis/nerd-fonts /tmp/nerd-fonts
        - /tmp/nerd-fonts/install.sh Ubuntu
        - /tmp/nerd-fonts/install.sh UbuntuMono
        - /tmp/nerd-fonts/install.sh Hack
        - rm -rf /tmp/nerd-fonts
