- ifmacos:
  - tap:
      - homebrew/cask-fonts
  - brew:
      - atool
  - cask:
      - font-hack-nerd-font
  - create:
      - ~/Library/Fonts
  - link:
      ~/Library/Fonts/fontawesome-webfont.ttf: fonts/fontawesome-webfont.ttf
      ~/Library/Fonts/Monaco-Powerline.otf: fonts/Monaco-Powerline.otf

- ifubuntu:
    - apt:
        - atool
    - create:
        - ~/.fonts
    - link:
        ~/.fonts/fontawesome-webfont.ttf: fonts/fontawesome-webfont.ttf
        ~/.fonts/Monaco-Powerline.otf: fonts/Monaco-Powerline.otf
    - shell:
        - ["bash ./fonts/download_install_font.sh", "Downloading Ubuntu fonts"]
