# --- Git Configuration ---
- ifubuntu:
    - apt:
        - git

- ifarch:
    - pacman:
        - git

- ifmacos:
    - brew:
        - git

- template:
    - ~/.gitconfig:
        source_file: git/gitconfig
        params:
          NAME: Subho Banerjee
          EMAIL: ssbanerje@gmail.com
          GITHUB_USERNAME: ssbanerje
          SIGNING_KEY: 02AF2E69BA7B1C8B
          SMTP_SERVER: smtp.gmail.com
          SMTP_PORT: 587
          SMTP_ENCRYPTION: tls
          __UNAME__:
            CREDENTIAL_HELPER:
              Darwin: osxkeychain
              Linux: cache --timeout 36000

- link:
    ~/.gitattributes: git/gitattributes

- shell:
    - rm -f ~/.global_gitignore;
    - >
      for f in Archives Backup Diff Dropbox Linux Vim Xcode macOS; do
        cat git/gitignore/Global/$f.gitignore >> ~/.global_gitignore
      done
