- ifubuntu:
    - apt:
        - i3
        - i3status
        - rofi
        - xss-lock
        - i3lock-fancy
        - network-manager-gnome
        - blueman
        - pulseaudio-utils

- ifarch:
    - pacman:
        - i3
        - i3status
        - rofi
        - xss-lock
        - networkmanager
        - blueman
        - pulseaudio
    - yay:
        - polybar
        - i3lock-fancy


- create:
    - ~/.config/i3
    - ~/.config/i3status
    - ~/.config/polybar

- link:
    ~/.config/i3/config: i3wm/i3.conf
    ~/.config/i3status/config: i3wm/i3status.conf
    ~/.config/polybar/config: i3wm/polybar.conf
    ~/.config/polybar/launch.sh: i3wm/polybar_launch.sh
