# Install software
- ifmacos:
    - cask:
        - kitty
- ifubuntu:
    - apt:
        - kitty
- ifarch:
    - pacman:
        - kitty

# Install config
- create:
    - ~/.config/kitty
- link:
    ~/.config/kitty/kitty.conf: kitty/kitty.conf
