- bootstraphomebrew:

- tap:
  - homebrew/cask-fonts

- brew:
  # Shell
  - ack
  - the_silver_searcher
  - fasd
  - bash
  - bash-completion
  - fzf
  - coreutils
  # Python
  - python
  # Archive
  - atool

- cask:
  - dozer
  - hammerspoon
  - iterm2
  - font-hack-nerd-font

- create:
    - ~/.config
    - ~/Library/Preferences

- link:
    ~/.hammerspoon: macos/hammerspoon

- shell:
    # Setup iterm2
    - "/bin/cp -f macos/com.googlecode.iterm2.plist ~/Library/Preferences/com.googlecode.iterm2.plist"
    - "curl -L https://iterm2.com/shell_integration/zsh -o ~/.config/iterm2_shell_integration.zsh"
    - "curl -L https://iterm2.com/shell_integration/bash -o ~/.config/iterm2_shell_integration.bash"
    - "./macos/macos.sh"
