- bootstraphomebrew:

- brew:
  - python

- cask:
  - dozer
  - hammerspoon
  - iterm2

- create:
    - ~/.config
    - ~/Library/Preferences

- link:
    ~/.hammerspoon: hammerspoon

- shell:
    - "command cp -f iterm2/com.googlecode.iterm2.plist ~/Library/Preferences/com.googlecode.iterm2.plist"
    - "curl -L https://iterm2.com/shell_integration/zsh -o ~/.config/iterm2_shell_integration.zsh"
    - "curl -L https://iterm2.com/shell_integration/bash -o ~/.config/iterm2_shell_integration.bash"
    - "./scripts/macos.sh"
