# --- Ranger Configuration ---
- pip:
    file: ranger/requirements.txt
    user: true
    stdout: false
    stderr: true


- ifubuntu:
    - apt:
        - file
        - highlight

- ifarch:
    - pacman:
        - file
        - highlight

- ifmacos:
    - brew:
        - highlight

- create:
    - ~/.config/ranger

- link:
    ~/.config/ranger/rifle.conf: ranger/rifle.conf
    ~/.config/ranger/rc.conf: ranger/rc.conf
    ~/.config/ranger/commands.py: ranger/commands.py

- shell:
    - ["[ ! -d ~/.config/ranger/plugins/ranger_devicons ] && git clone https://github.com/alexanderjeurissen/ranger_devicons ~/.config/ranger/plugins/ranger_devicons", "Install Ranger Icons"]
