# ------------------ Install software
- ifubuntu:
    - apt:
        - zsh
        - fzf
        - silversearcher-ag
        - grc
        - ack

- ifarch:
    - pacman:
        - zsh
        - fzf
        - the_silver_searcher
        - grc
        - ack

- ifmacos:
    - tap:
        - homebrew/command-not-found
    - brew:
        - zsh
        - bash-completion
        - fzf
        - coreutils
        - the_silver_searcher
        - grc
        - ack

# ------------------ Install configuration
- create:
    - ~/.config

- link:
    ~/.config/base16-shell: shell/base16-shell
    ~/.config/antigen.zsh: shell/antigen.zsh
    ~/.config/antigenrc: shell/antigenrc
    ~/.zshrc: shell/zshrc
    ~/.p10k.zsh: shell/p10k.zsh
    ~/.bashrc: shell/bashrc
    ~/.config/bash.prompt.sh: shell/bash.prompt.sh
    ~/.config/env.sh: shell/env.sh
    ~/.config/aliases.sh: shell/aliases.sh

    ~/.hushlogin: shell/hushlogin
    ~/.ackrc: shell/ackrc
    ~/.curlrc: shell/curlrc
    ~/.gdbinit: shell/gdbinit
    ~/.gdbinit.local: shell/gdbinit.local
    ~/.wgetrc: shell/wgetrc
    ~/.pythonrc.py: shell/pythonrc.py

- shell:
    - ["zsh -i -c exit", "Install ZSH plugins"]
