# --- Shell Configuration ---
- ifubuntu:
    - apt:
        - zsh
        - fzf
        - silversearcher-ag

- ifarch:
    - pacman:
        - zsh
        - fzf
        - the_silver_searcher

- ifmacos:
    - tap:
        - homebrew/command-not-found
    - brew:
        - zsh
        - bash-completion
        - fzf
        - coreutils
        - the_silver_searcher

- pip:
    file: shell/requirements.txt
    user: true
    stdout: false
    stderr: true

- link:
    ~/.config/antigen.zsh: shell/antigen.zsh
    ~/.config/antigenrc: shell/antigenrc
    ~/.zshrc: shell/zshrc
    ~/.p10k.zsh: shell/p10k.zsh
    ~/.bashrc: shell/bashrc
    ~/.config/bash_prompt.sh: shell/bash_prompt.sh
    ~/.config/env.sh: shell/env.sh
    ~/.config/aliases.sh: shell/aliases.sh
    ~/.hushlogin: shell/hushlogin
    ~/.curlrc: shell/curlrc
    ~/.gdbinit: shell/gdbinit
    ~/.wgetrc: shell/wgetrc

- shell:
    - ["zsh -i -c exit", "Install ZSH plugins"]
