# --- Terminal Emulator Configuration ---
- ifmacos:
    - tap:
        - homebrew/cask-fonts
    - cask:
        - kitty
        - iterm2
        - font-hack-nerd-font
- ifubuntu:
    - apt:
        - kitty
- ifarch:
    - pacman:
        - kitty
- ifanylinux:
    - shell:
        - git clone https://github.com/ryanoasis/nerd-fonts /tmp/nerd-fonts
        - /tmp/nerd-fonts/install.sh Hack
        - rm -rf /tmp/nerd-fonts

- create:
    - ~/.config/kitty
- link:
    ~/.config/kitty/kitty.conf: kitty/kitty.conf
    ~/.config/kitty/macos-launch-services-cmdline:
      if: '[ `uname` = Darwin ]'
      path: kitty/macos-launch-services-cmdline

- ifmacos:
    - create:
        - ~/Library/Preferences
    - shell:
        - "command cp -f iterm2/com.googlecode.iterm2.plist ~/Library/Preferences/com.googlecode.iterm2.plist"
        - "curl -L https://iterm2.com/shell_integration/zsh -o ~/.config/iterm2_shell_integration.zsh"
        - "curl -L https://iterm2.com/shell_integration/bash -o ~/.config/iterm2_shell_integration.bash"
