# --- TMUX Configuration ---
- ifubuntu:
    - apt:
        - tmux

- ifarch:
    - pacman:
        - tmux

- ifmacos:
    - brew:
        - tmux
        - reattach-to-user-namespace

- create:
  - ~/.tmux/plugins

- link:
    ~/.tmux.conf: tmux/tmux.conf
    ~/.tmux/plugins/tpm: tmux/tpm
    ~/.tmux-macos.conf:
      if: '[[ $(uname -s) = Darwin ]]'
      path: tmux/tmux-macos.conf
