# --- Ubuntu Base Configuration ---
- ifubuntu:
    - aptupdate:

    - apt:
        - sudo
        - curl
        - python3-dev
        - python3-pip
        - git
        - build-essential
        - software-properties-common
