#!/usr/bin/env zsh

# Load oh-my-zsh library
antigen use oh-my-zsh

# Mac specific plugins
if [ "$(uname)"="Darwin" ]; then
  antigen bundle osx
  antigen bundle brew
  antigen bundle iterm2
  antigen bundle gnu-utils
fi

# Linux specific plugins
if [ "$(uname)"="Linux" ]; then
  if command -v apt-get &> /dev/null; then # This is ubuntu
    antigen bundle debian
    antigen bundle ubuntu
  elif command -v pacman &> /dev/null; then # This is archlinux
    antigen bundle archlinux
  fi
fi

# Load bundles from the default repo (oh-my-zsh)
antigen bundle cargo
antigen bundle colored-man-pages
antigen bundle colorize
antigen bundle command-not-found
antigen bundle common-aliases
antigen bundle docker
antigen bundle extract
antigen bundle fancy-ctrl-z
antigen bundle fzf
antigen bundle git-escape-magic
antigen bundle gitfast
antigen bundle mosh
antigen bundle npm
antigen bundle pip
antigen bundle python
antigen bundle rust
antigen bundle rustup
# antigen bundle sbt
# antigen bundle scala
antigen bundle tmux
antigen bundle vscode
antigen bundle web-search
antigen bundle yarn

# Load bundles from external repos
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle jeffreytse/zsh-vi-mode
antigen bundle romkatv/zsh-defer

# Select theme
antigen theme romkatv/powerlevel10k
# antigen theme afowler

# Tell Antigen that you're done
antigen apply

# vi: ft=zsh
