#!/usr/bin/env bash

# Bash Options {{{
#Control history saves
HISTCONTROL=ignoreboth:ignoredups:ignorespace
shopt -s histappend

# Make bash check its window size after a process completes
shopt -s checkwinsize
# }}}

# Helper function {{{

function CHECK_AND_SOURCE() {
  while [[ "$#" -ne 0 ]]; do
    if [[ -r "$1" ]]; then
      source "$1"
    fi
    shift
  done
}

# }}}

# Environment variables
CHECK_AND_SOURCE \
  "$HOME/.config/env.sh" \
  "$HOME/.config/aliases.sh"

# Skip the remaining file for non-interactive shells
if [[ "$-" != *i* ]]; then
  unset CHECK_AND_SOURCE
  return
fi

# Bash Completion + Keybindings {{{

if [[ "${UNAME:=$(uname -s)}" == "Linux" ]]; then
  CHECK_AND_SOURCE \
    "$(shopt -oq posix || echo '/usr/share/bash-completion/bash_completion')" \
    /usr/share/doc/fzf/examples/completion.bash \
    /usr/share/doc/fzf/examples/key-bindings.bash \
    /etc/grc.sh
elif [[ "${UNAME:=$(uname -s)}" == "Darwin" ]]; then
  CHECK_AND_SOURCE \
    "${BREW_PREFIX:=$(brew --prefix)}/etc/profile.d/bash_completion.sh" \
    "$BREW_PREFIX/opt/fzf/shell/completion.bash" \
    "$BREW_PREFIX/opt/fzf/shell/key-bindings.bash" \
    "$BREW_PREFIX/etc/grc.sh" \
    $([[ "$term_program" == "iterm.app" ]] && echo "$HOME/.config/iterm2_shell_integration.bash")
fi

# }}}

# Set vi mode
set -o vi

# Theme
CHECK_AND_SOURCE \
  "$HOME/.config/bash.prompt.sh"

unset CHECK_AND_SOURCE

# vim:foldmethod=marker
