# Check if this is an interactive shell
if [ -z "$PS1" ]; then
   return
fi

#Control history saves
HISTCONTROL=ignoreboth:ignoredups:ignorespace
shopt -s histappend

#Set reverse and forward search for arrow keys
bind '"\e[A"':history-search-backward
bind '"\e[B"':history-search-forward

# Make bash check its window size after a process completes
shopt -s checkwinsize

# Source platform specific"
source "$HOME/.config/bashrc.$(uname).sh"

# Source common settings"
source "$HOME/.config/common_settings.sh"

# Setup prompt
source "$HOME/.config/bash.prompt.sh"
