#!/usr/bin/env zsh

# Skip all this for non-interactive shells
[[ -z "$PS1" ]] && return

setopt LOCAL_OPTIONS
setopt LOCAL_TRAPS
setopt SHARE_HISTORY
setopt CORRECT
setopt COMPLETE_ALIASES
setopt COMPLETE_IN_WORD
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_REDUCE_BLANKS

# Homebrew
if (( ! ${fpath[(I)/usr/local/share/zsh/site-functions]} )); then
  FPATH="/usr/local/share/zsh/site-functions:$FPATH"
fi

# Load antigen
export POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
source "$HOME/.config/antigen.zsh"
antigen init "$HOME/.config/antigenrc"

# Make fancy-ctrl-z work with zvm
zvm_define_widget fancy-ctrl-z fancy-ctrl-z
zvm_bindkey viins '^Z' fancy-ctrl-z

# Completion for kill
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#) ([0-9a-z-]#)*=01;34=0=01'
zstyle ':completion:*:*:*:*:processes' command "ps -u $(whoami) -o pid,user,comm -w -w"

# Completion for ssh
zstyle ':completion:*:ssh:*' tag-order hosts users
zstyle ':completion:*:ssh:*' group-order hosts-domain hosts-host users hosts-ipaddr

# ignore completion functions (until the _ignored completer)
zstyle ':completion:*:functions' ignored-patterns '_*'

# completing process IDs with menu selection
zstyle ':completion:*:*:kill:*' menu yes select

# Source stuff
source "$HOME/.config/zshrc.$(uname -s).sh"
source "$HOME/.config/fzf.sh"
source "$HOME/.config/common_settings.sh"
source "$HOME/.p10k.zsh"
