#!/usr/bin/env bash

set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIGDIR="${BASEDIR}/meta/config"
DOTBOT="${BASEDIR}/installer/dotbot/bin/dotbot"
PLUGINDIR="${BASEDIR}/installer/plugins"

# Parse arguments
while (( "$#" )); do
  case "$1" in
    -*|--*)
      FLAGS=$(echo -e "${FLAGS} $1" | sed -e 's/^[[:space:]]*//')
      ;;
    *)
      CONFIGS=$(echo -e "${CONFIGS} $1" | sed -e 's/^[[:space:]]*//')
      ;;
  esac
  shift
done

# Load configuration
for config in base $CONFIGS; do
    echo -e "Adding configuration $config"
    CONFIGCONTENT="${CONFIGCONTENT}\n$(<"${CONFIGDIR}/${config}.yaml")"
done

# Run dotbot
if [[ ! -z "${FLAGS}" ]]; then
  "${DOTBOT}" "${FLAGS}" -d "${BASEDIR}" --plugin-dir "${PLUGINDIR}" -c <(echo -e "${CONFIGCONTENT}")
else
  "${DOTBOT}" -d "${BASEDIR}" --plugin-dir "${PLUGINDIR}" -c <(echo -e "${CONFIGCONTENT}")
fi
