#!/usr/bin/env bash

set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIGDIR="${BASEDIR}/meta/config"
PROFILESDIR="${BASEDIR}/meta/profiles"
DOTBOT="${BASEDIR}/installer/dotbot/bin/dotbot"
PLUGINDIR="${BASEDIR}/installer/plugins"

# Parse arguement
while (( "$#" )); do
  case "$1" in
    -*|--*)
      FLAGS=$(echo -e "${FLAGS} $1" | sed -e 's/^[[:space:]]*//')
      ;;
    *)
      ARGS=$(echo -e "${ARGS} $1" | sed -e 's/^[[:space:]]*//')
      ;;
  esac
  shift
done
set -- $ARGS

# Read configs from profile
while IFS= read -r config; do
    CONFIGS+=" ${config}"
done < "${META_DIR}/${PROFILESDIR}/$1"
shift

# Load configurations
for config in ${CONFIGS} ${@}; do
    echo -e "Adding configuration $config"
    CONFIGCONTENT="${CONFIGCONTENT}\n$(<"${CONFIGDIR}/${config}.yaml")"
done

# Run dotbot
PLUGINS=$(cat <<-END
  --plugin-dir ${PLUGINDIR} --plugin-dir ${PLUGINDIR}/dotbot-ifplatform \
  --plugin-dir ${PLUGINDIR}/dotbot-template --plugin-dir ${PLUGINDIR}/dotbot-pip \
  --plugin-dir ${PLUGINDIR}/dotbot-sudo
END
)
if [[ ! -z "${FLAGS}" ]]; then
  "${DOTBOT}" "${FLAGS}" -d "${BASEDIR}" ${PLUGINS} -c <(echo -e "${CONFIGCONTENT}")
else
  "${DOTBOT}" -d "${BASEDIR}" ${PLUGINS} -c <(echo -e "${CONFIGCONTENT}")
fi
