#=============================================================================
# SpaceVim Configuration File
#=============================================================================

################################################# SPACEVIM CONFIG {{{1

[options]
  vimcompatible = false
  enable_debug = true
  automatic_update = true
  bootstrap_before = 'myspacevim#before'
  bootstrap_after = 'myspacevim#after'
  auto_disable_touchpad = true
  realtime_leader_guide = true

  colorscheme = 'material'
  colorscheme_bg = 'dark'
  enable_guicolors = true

  statusline_separator = 'arrow'
  statusline_inactive_separator = 'slant'
  enable_statusline_mode=true
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_os_fileformat_icon = true

  filemanager = "nerdtree"

  github_username = 'ssbanerje'

####################################################################}}}1

################################################### SPACEVIM PLUGINS {{{1

[[layers]]
  name = 'autocomplete'
  autocomplete_method = 'coc'
  auto-completion-return-key-behavior = 'complete'
  auto-completion-tab-key-behavior = 'smart'
  auto-completion-complete-with-key-sequence-delay = 0.1

[[layers]]
  name = 'colorscheme'

[[layers]]
  name = 'debug'

[[layers]]
  name = 'default'

[[layers]]
  name = 'denite'

[[layers]]
  name = 'edit'

[[layers]]
  name = 'git'
  git-plugin = 'gina'

[[layers]]
  name = 'gtags'

[[layers]]
  name = 'incsearch'

[[layers]]
  name = 'shell'
  default_position = 'bottom'

[[layers]]
  name = 'sudo'

[[layers]]
  name = "tools"

[[layers]]
  name = 'tmux'

[[layers]]
  name = 'VersionControl'

####################################################################}}}1

################################################# LANGUAGE PLUGINS {{{1

[[layers]]
  name = 'lang#assembly'

[[layers]]
  name = 'lang#c'
  enable_clang_syntax_highlight = true
  [layer.clang_std]
    c = 'c11'
    cpp = 'c++17'

[[layers]]
  name = 'lang#dockerfile'

[[layers]]
  name = 'lang#extra'

[[layers]]
  name = 'lang#html'

[[layers]]
  name = 'lang#latex'

[[layers]]
  name = "lang#lua"

[[layers]]
  name = 'lang#markdown'

[[layers]]
  name = 'lang#python'
  format-on-save = true

[[layers]]
  name = 'lang#rust'
  format-autosave = 1

[[layers]]
  name = 'lang#scala'

[[layers]]
  name = "lang#sh"

[[layers]]
  name = 'lang#toml'

[[layers]]
  name = 'lang#vim'

[[layers]]
  name = 'lsp'
  filetypes = [
    'c',
    'cpp',
    'rust',
    'python',
    'sh',
    'html',
  ]
  [layers.override_cmd]
    rust = ['rls']

####################################################################}}}1

################################################# CUSTOM PLUGINS {{{1

[[layers]]
  name = 'my_motions'

####################################################################}}}1

# vim: set fdm=marker:
