#!/usr/bin/env bash

#------------------------------------------ Tiling -------------------------------------------------
yabai -m config layout                       bsp
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config padding                      0:0:0:0
yabai -m config window_gap                   0

yabai -m config window_placement             second_child

yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0

yabai -m config window_shadow                float

yabai -m config window_border                off
yabai -m config active_window_border_topmost off
yabai -m config window_border_placement      inset
yabai -m config window_border_width          5
yabai -m config window_border_radius         1.0
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f

yabai -m config mouse_follows_focus          on        # off
yabai -m config focus_follows_mouse          autofocus # off
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize


#------------------------------------------ Rules --------------------------------------------------
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="Music" app="^Music$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="FaceTime" app="^FaceTime$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Hammerspoon" app="^Hammerspoon$" manage=off
yabai -m rule --add label="CleanMyMac X" app="^CleanMyMac X$" manage=off
yabai -m rule --add label="Zoom" app="^zoom.us$" manage=off
yabai -m rule --add label="Skype" app="^Skype$" manage=off

printf "yabai: configuration loaded...\\n"
