#!/usr/bin/env bash

set -x

#------------------------------------------ Tiling -------------------------------------------------
yabai -m config layout                      bsp
yabai -m config split_ratio                 0.50
yabai -m config auto_balance                on
yabai -m config window_placement            second_child
yabai -m config window_border               off

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off
yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize


#------------------------------------------ Rules --------------------------------------------------
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Hammerspoon" app="^Hammerspoon$" title=".*" manage=off


set +x
printf "yabai: configuration loaded...\\n"
