- bootstraphomebrew:

- tap:
  - homebrew/cask-fonts

- brew:
  # Shell
  - tmux
  - reattach-to-user-namespace
  - git
  - ack
  - ag
  - fasd
  - bash-completion
  - ranger
  - fzf
  - coreutils
  # Editors
  - neovim
  # Language
  - ctags
  - node
  - yarn
  - global
  # Python
  - python
  # Archive
  - atool

- cask:
  - dozer
  - hammerspoon
  - iterm2
  - font-hack-nerd-font
