- create:
    - ~/.config
    - ~/Library/Preferences

- link:
    ~/.hammerspoon: osx/hammerspoon

- shell:
  - "cp -f osx/com.googlecode.iterm2.plist ~/Library/Preferences/com.googlecode.iterm2.plist"
  - "curl -L https://iterm2.com/shell_integration/zsh -o ~/.config/iterm2_shell_integration.zsh"
  - "curl -L https://iterm2.com/shell_integration/bash -o ~/.config/iterm2_shell_integration.bash"
