---
name: Check Installer Scripts

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-profiles:  # {{{
    name: Test Profiles
    strategy:
      matrix:
        include:
          - {profile: macos, os: macOS-latest}
          - {profile: ubuntu, os: ubuntu-latest}
          - {profile: ubuntu-minimal, os: ubuntu-latest}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dotfiles
        run: ./install_profile -vv ${{ matrix.profile }}
  # }}}

  build-container-ubuntu:  # {{{
    name: Build Ubuntu Containers
    needs: [test-profiles]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REGISTRY_PAT }}
      - name: Build Ubuntu Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.ubuntu
          platforms: linux/amd64
          build-args: |
            user=dotuser
            uid=1000
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:ubuntu
          push: true
      - name: Build Mac Ubuntu Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.ubuntu
          platforms: linux/amd64
          build-args: |
            user=dotuser
            uid=501
          tags: |
            ghcr.io/${{ github.repository }}:ubuntu-mac
          push: true
  # }}}

  build-container-arch:  # {{{
    name: Build Archlinux Containers
    needs: [test-profiles]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REGISTRY_PAT }}
      - name: Build Archlinux Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.archlinux
          platforms: linux/amd64
          build-args: |
            user=dotuser
            uid=1000
          tags: ghcr.io/${{ github.repository }}:archlinux
          push: true
      - name: Build Mac Archlinux Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.archlinux
          platforms: linux/amd64
          build-args: |
            user=dotuser
            uid=501
          tags: |
            ghcr.io/${{ github.repository }}:archlinux-mac
          push: true
  # }}}

...
# vim: set fdm=marker:
