---
name: Check Installer Scripts

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-profiles:  # {{{
    name: Test Profiles
    strategy:
      matrix:
        include:
          - {profile: macos, os: macOS-latest}
          - {profile: ubuntu, os: ubuntu-latest}
          - {profile: ubuntu-minimal, os: ubuntu-latest}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Initialize dependencies
        run: |
          [[ -f /usr/local/bin/2to3 ]] && rm -rf /usr/local/bin/2to3  # TODO: HOEMBREW ERROR
          pip install pyyaml jinja2 distro
          git config --global core.symlinks false
      - name: Install dotfiles
        run: ./install_profile -vv ${{ matrix.profile }}
  # }}}

  build-docker:  # {{{
    name: Build Docker Containers
    needs: [test-profiles]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REGISTRY_PAT }}
      - name: Build Ubuntu Container
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:ubuntu
          file: Dockerfile.ubuntu
      - name: Build ArchLinux Container
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}:archlinux
          file: Dockerfile.archlinux
  # }}}

...
# vim: set fdm=marker:
