name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Initialize dotfiles
        run: pip install pyyaml jinja2
      - name: Install dotfiles
        run: ./install_profile ubuntu

  run-on-macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Initialize dotfiles
        run: pip install jinja2 pyyaml
      - name: Install dotfiles
        run: ./install_profile macos
