name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install-config:
    strategy:
      matrix:
        config:
          - base
          - ubuntu
          - macos
          - pip
          - yarn
          - bin
          - tmux
          - ssh
          - editors
          - git
          - shell
          - fonts
          - ranger
        os:
          - ubuntu-latest
          - macOS-latest
        exclude:
          - config: ubuntu
            os: macOS-latest
          - config: macos
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Initialize dotfiles
        run: pip install pyyaml jinja2
      - name: Install dotfiles
        run: ./install ${{ matrix.config }}

  install-profile:
    needs: [install-config]
    strategy:
      matrix:
        profile:
          - ubuntu
          - macos
        os:
          - ubuntu-latest
          - macOS-latest
        exclude:
          - profile: ubuntu
            os: macOS-latest
          - profile: macos
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Initialize dotfiles
        run: pip install pyyaml jinja2
      - name: Install dotfiles
        run: ./install_profile ${{ matrix.profile }}

