---
name: Publish Docker Image

on:
  repository_dispatch:
    types:
      - build_container

jobs:
  push_to_registry:
    name: Push docker image to container registry
    runs-on: ubuntu-latest
    steps:
      - uses: haya14busa/action-cond@v1
        id: branch
        with:
          cond: ${{ github.event.client_payload.branch == null }}
          if_true: ''
          if_false: ${{ github.event.client_payload.branch }}
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.branch.outputs.value }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/ppc64le
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
...
